spring:
  application:
    name: authentication

server:
  servlet:
    context-path: /auth
  port: 8083

api:
  user: ${USER_URL}/user

jwt:
  config:
    login-url: /auth/login

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8084/eureka/}
  instance:
    preferIpAddress: true
