spring:
  application:
    name: user
  datasource:
    url: jdbc:postgresql://localhost:5432/cloudcash
    username: root
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  servlet:
    context-path: /user
  port: 8080
