spring:
  application:
    name: user
  datasource:
    url: jdbc:postgresql://${POSTGRE_HOST}:5432/cloudcash
    username: ${POSTGRE_USER}
    password: ${POSTGRE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: ${KAFKA_LOCAL:kafka:29092}
    consumer:
      group-id: payment-balance-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      max-poll-records: 10
    listener:
      missing-topics-fatal: false
    admin:
      auto-create: true
    topics:
      balance:
        name: balance-topic
        partitions: 3
        replication-factor: 1


topics:
  balance: balance-topic

server:
  servlet:
    context-path: /user
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI}
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.cloud.client.hostname}:${server.port}
