spring:
  application:
    name: transfer
  kafka:
    bootstrap-servers: localhost:9093
    producer:
      acks: all
      retries: 3
    listener:
      missing-topics-fatal: false
    admin:
      auto-create: true
    topics:
      payment-topic:
        partitions: 1
        replication-factor: 1

topics:
  payment: payment-topic

server:
  servlet:
    context-path: /transfer
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8084/eureka/}
  instance:
    preferIpAddress: true
