spring:
  application:
    name: payment
  kafka:
    bootstrap-servers: localhost:9093
    producer:
      acks: all
      retries: 3
    listener:
      missing-topics-fatal: false
    admin:
      auto-create: true
    topics:
      payment-topic:
        partitions: 1
        replication-factor: 1

topics:
  payment: payment-topic

server:
  servlet:
    context-path: /payment
  port: 8081


api:
  user: ${USER_URL}/user
