spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
        - id: transfer-service
          uri: lb://TRANSFER
          predicates:
            - Path=/transfer/**
        - id: user-service
          uri: lb://USER
          predicates:
            - Path=/user/**
    discovery:
      enabled: true
  web:
    resources:
      add-mappings: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8083

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.mvc: DEBUG

jwt:
  config:
    login-url: /login

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8084/eureka/}
  instance:
    preferIpAddress: true
