spring:
  application:
    name: payment
  kafka:
    bootstrap-servers: localhost:9093
    producer:
      acks: all
      retries: 3
    consumer:
      group-id: transfer-payment-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      max-poll-records: 10
    listener:
      missing-topics-fatal: false
    admin:
      auto-create: true
  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: password
      database: cloud_cash
      authentication-database: admin

topics:
  payment: payment-topic
  balance: balance-topic

server:
  servlet:
    context-path: /payment
  port: 8082


api:
  user: ${USER_URL}/user

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8084/eureka/}
  instance:
    preferIpAddress: true
